FROM node:22

RUN apt-get update && apt-get install -y \
  ffmpeg \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm install


COPY tsconfig*.json ./
COPY nest-cli.json ./

COPY . .

RUN npm run build

EXPOSE 3000
CMD sh -c "npm run migrate && npm run seed && node dist/src/main.js"
